# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWmNo4DN_wC2mEu50AuSL_ZpIw6HmGhm
"""

!pip install qrcode[pil]

import qrcode
from google.colab import files

def generar_qr(texto):
    qr = qrcode.make(texto)
    qr.save("qr.png")
    files.download("qr.png")

texto = input("texto: ")
generar_qr(texto)